import { db } from '../config/firebase';
import { collection, getDocs, deleteDoc, addDoc, doc } from 'firebase/firestore';

const quartersData = [
  // A-type quarters
  { number: 'A-1', type: 'A-type', status: 'vacant', location: 'Block A' },
  { number: 'A-2', type: 'A-type', status: 'vacant', location: 'Block A' },
  { number: 'A-3', type: 'A-type', status: 'vacant', location: 'Block A' },

  // MB-type quarters
  { number: 'MB-1A', type: 'MB-type', status: 'vacant', location: 'Block MB' },
  { number: 'MB-1B', type: 'MB-type', status: 'vacant', location: 'Block MB' },
  { number: 'MB-2A', type: 'MB-type', status: 'vacant', location: 'Block MB' },
  { number: 'MB-2B', type: 'MB-type', status: 'vacant', location: 'Block MB' },
  { number: 'MB-3A', type: 'MB-type', status: 'vacant', location: 'Block MB' },
  { number: 'MB-3B', type: 'MB-type', status: 'vacant', location: 'Block MB' },

  // B-type quarters
  { number: 'B-1', type: 'B-type', status: 'vacant', location: 'Block B' },
  { number: 'B-2', type: 'B-type', status: 'vacant', location: 'Block B' },
  { number: 'B-3', type: 'B-type', status: 'vacant', location: 'Block B' },
  { number: 'B-4', type: 'B-type', status: 'vacant', location: 'Block B' },

  // C-type quarters (first part)
  { number: 'C-1', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-2', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-3', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-4', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-5', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-6', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-7', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-8', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-9', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-10', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-11', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-12', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-13', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-14', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-15', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-16', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-17', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-18', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-19', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-20', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-21', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-22', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-23', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-24', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-25', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-26', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-27', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-28', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-29', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-30', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-31', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-32', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-33', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-34', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-35', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-36', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-37', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-38', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-39', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'C-40', type: 'C-type', status: 'vacant', location: 'Block C' },
  { number: 'MC-1A', type: 'MC-type', status: 'vacant', location: 'Block MC' },
  { number: 'MC-1B', type: 'MC-type', status: 'vacant', location: 'Block MC' },
  { number: 'MC-1C', type: 'MC-type', status: 'vacant', location: 'Block MC' },
  { number: 'MC-1D', type: 'MC-type', status: 'vacant', location: 'Block MC' },
  { number: 'MC-1E', type: 'MC-type', status: 'vacant', location: 'Block MC' },
  { number: 'MC-1F', type: 'MC-type', status: 'vacant', location: 'Block MC' },

  // G-type quarters
  { number: 'G/A-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-9', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-10', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-11', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/A-12', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-9', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-10', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-11', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/B-12', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-9', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-10', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-11', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-12', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-13', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-14', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-15', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/C-16', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-9', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-10', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-11', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-12', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-13', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-14', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-15', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/D-16', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-9', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-10', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-11', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-12', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-13', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-14', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-15', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/E-16', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-9', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-10', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-11', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-12', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-13', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-14', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-15', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/F-16', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/G-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/G-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/G-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/G-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/H-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/H-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/H-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/H-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/H-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/H-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/I-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/I-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/I-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/I-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/I-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/I-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/I-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/I-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/J-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/J-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/J-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/J-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/J-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/K-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/K-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/K-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/K-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/K-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/K-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/K-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/K-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/L-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/L-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/L-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/L-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-1', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-2', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-3', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-4', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-5', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-6', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-7', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-8', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-9', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-10', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-11', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-12', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-13', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-14', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-15', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-16', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-17', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-18', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-19', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-20', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-21', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-22', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-23', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-24', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-25', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-26', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-27', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-28', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-29', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-30', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-31', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-32', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-33', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-34', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-35', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-36', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-37', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-38', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-39', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-40', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-41', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-42', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-43', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-44', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-45', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-46', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-47', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-48', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-49', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-50', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-51', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-52', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-53', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-54', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-55', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-56', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-57', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-58', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-59', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-60', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-61', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-62', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-63', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/VII-64', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/48', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/49', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/50', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/51', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/52', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/53', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/54', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/55', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/56', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/57', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/58', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/60', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/61', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/62', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/63', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/65', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/67', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/69', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/71', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/73', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/75', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/77', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/5-21', type: 'G-type', status: 'vacant', location: 'Block G' },
  { number: 'G/5-22', type: 'G-type', status: 'vacant', location: 'Block G' },

  // H-type quarters
  { number: 'H-1', type: 'H-type(MS)', status: 'vacant', location: 'Block H' },
  { number: 'H-10', type: 'H-type(MS)', status: 'vacant', location: 'Block H' },
  { number: 'H-100', type: 'H-type(MS)', status: 'vacant', location: 'Block H' },
  { number: 'H-101', type: 'H-type(MS)', status: 'vacant', location: 'Block H' }
];

export const initializeQuarters = async () => {
  try {
    // Get reference to quarters collection
    const quartersRef = collection(db, 'quarters');
    
    // Get all existing quarters
    const existingQuarters = await getDocs(quartersRef);
    
    // Delete all existing quarters
    const deletePromises = existingQuarters.docs.map(doc => 
      deleteDoc(doc.ref)
    );
    await Promise.all(deletePromises);
    
    // Add new quarters
    const addPromises = quartersData.map(quarter => 
      addDoc(quartersRef, {
        ...quarter,
        createdAt: new Date(),
        updatedAt: new Date()
      })
    );
    
    await Promise.all(addPromises);
    console.log('Successfully initialized quarters');
    return true;
  } catch (error) {
    console.error('Error initializing quarters:', error);
    return false;
  }
}; 